apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    name: es
spec:
  version: 7.15.2
  nodeSets:
  - name: default
    config:
        node.store.allow_mmap: false
    count: 2

